# Generated by Django 4.2 on 2023-04-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cquantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'circle',
            },
        ),
    ]
